disabled = false
languageCode = "fr"
languageName = "Français"
weight = 1
title = "Entre deux lignes"

[params]
  displayName = "Français"
  isoCode = "fr"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logo.svg"
  description = "Blog sur le make your own gear (MYOG), l'impression 3D mais aussi le vélo et en particulier le VTT."

  ["params.author"]
    name = "Christophe Le Douarec"
    image = "LE DOUAREC Christophe.jpg"
    headline = "Leader technique expérimenté, avec une solide expérience dans les systèmes embarqués et l’amélioration organisationnelle, au sein d'équipes R&D au service des objectifs business."
    bio = "Leader technique expérimenté, avec une solide expérience dans les systèmes embarqués et l’amélioration organisationnelle, au sein d'équipes R&D au service des objectifs business."
    links = [
      { github = "https://github.com/cledouarec" },
      { printables = "https://www.printables.com/@CelineChrist_1939241" },
    ]