colorScheme = "avocado"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableA11y = false
enableSearch = true
enableCodeCopy = true
enableStructuredBreadcrumbs = false
replyByEmail = false
mainSections = ["posts"]
disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
defaultBackgroundImage = "background.webp"
backgroundImageWidth = 1920
hotlinkFeatureImage = false
fingerprintAlgorithm = "sha512"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v11.next.forgejo.org"
firebase = { }
fathomAnalytics = { }
selineAnalytics = { }
buymeacoffee = { }
verification = { }
rssnext = { }
advertisement = { }
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "background"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "/posts/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true
  disableHeroImageFilter = false

[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showCategoryOnly = false
  showAuthorsBadges = false
  showWordCount = false
  showZenMode = true
  sharingLinks = [ "reddit", "twitter", "mastodon", "bluesky", "facebook", "email"]

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = false
  showBreadcrumbs = false
  showSummary = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[sitemap]
  excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "thumbAndBackground"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false

[umamiAnalytics]
  websiteid = "b9aae1fe-86a5-402e-933b-ac9f02515679"